name: Pyramid

on: push

jobs:
  pyramid:
    runs-on: ubuntu-latest

    steps:
       - name: Print pyramid
         run: |
          for i in {1..10}
          do
            printf "%*s\n" $i | tr " " "*"
          done